import type { KeywordPageData } from "./keyword-page";

export const keywordPagesA: KeywordPageData[] = [
  {
    slug: "air-conditioning-service-los-angeles",
    title: "Air Conditioning Service in Los Angeles | Bernardino Martin HVAC",
    metaDescription: "Professional air conditioning service in Los Angeles. Call 818-400-0227.",
    heroLabel: "Cooling Services",
    heroTitle: "Air Conditioning Service in Los Angeles",
    heroSubtitle: "Responsive cooling service, tune-ups, and system care for Los Angeles homes that rely on dependable comfort through long hot seasons.",
    heroImage: { src: "/images/real-ac-service.webp", alt: "Technician servicing an air conditioning system in Los Angeles" },
    introHeading: "Cooling Service That Matches Los Angeles Heat",
    introParagraphs: [
      "Air conditioning service in Los Angeles has to be practical, responsive, and built around real summer demand. Bernardino Martin provides air conditioning service for homeowners who want stronger cooling, cleaner airflow, and fewer surprises when temperatures rise. Whether the system is in a family home in the Valley or a smaller property in central Los Angeles, regular service helps keep it ready for long run times and heavy use.",
      "A professional cooling visit should look beyond the surface. We review airflow, drain conditions, thermostat operation, major electrical components, and the overall health of the system so homeowners understand how the equipment is actually performing. In Los Angeles, dust, high runtime, and older duct systems can all reduce comfort and quietly increase operating cost.",
      "Our service approach focuses on reliability and clarity. Some customers need a seasonal tune-up before peak heat, while others need stronger maintenance habits because the system has been pushed hard for years. Bernardino Martin helps Los Angeles homeowners improve comfort and reduce breakdown risk with service that feels polished, local, and genuinely useful.",
    ],
    galleryHeading: "Recent air conditioning service and cooling system work",
    galleryImages: [
      { src: "/images/real-ac-service.webp", alt: "Air conditioning service at an outdoor condenser" },
      { src: "/images/svc-hvac-maint.webp", alt: "Routine cooling maintenance on a residential HVAC system" },
      { src: "/images/real-diagnostics.webp", alt: "Diagnostic inspection for air conditioning performance" },
      { src: "/images/svc-install-ac.webp", alt: "Professional installation and service support for AC equipment" },
    ],
    systemsHeading: "Systems We Service and Optimize",
    systemsIntro: "We support high-efficiency air conditioning systems, inverter-based cooling equipment, ducted comfort systems, and mini-split applications used throughout Los Angeles.",
    systems: [
      { title: "High-efficiency AC systems", description: "We maintain modern cooling systems designed to reduce operating costs while keeping indoor temperatures stable during long hot spells." },
      { title: "Variable-speed comfort systems", description: "Variable-speed systems need careful setup and servicing to deliver quiet performance, balanced airflow, and better humidity control." },
      { title: "Ducted whole-home cooling", description: "For homes with central air, we inspect equipment and supporting airflow conditions so the system can cool consistently from room to room." },
      { title: "Hybrid cooling upgrades", description: "We help Los Angeles homeowners pair service work with smart thermostat and airflow upgrades that improve comfort without a full replacement." },
    ],
    inlineHeading: "Comfort service that improves reliability, not just appearances",
    inlineBody: "A cooling system that looks clean on the outside can still suffer from weak airflow, poor calibration, or worn electrical parts. We service Los Angeles air conditioning systems with attention to performance, energy use, and day-to-day comfort so homeowners get results they can feel after the appointment is over.",
    inlineImage: { src: "/images/svc-hvac-maintenance-new.png", alt: "Indoor air conditioning service and maintenance work" },
    servicesHeading: "What our Los Angeles air conditioning service includes",
    services: [
      "Cooling diagnostics and performance testing",
      "Preventive maintenance and seasonal tune-ups",
      "Airflow review and thermostat calibration",
      "Condenser and coil service recommendations",
      "Drain line and moisture checks",
      "Repair planning for older cooling systems",
      "Filter and circulation guidance",
      "Same-day service scheduling when available",
    ],
    trustHeading: "Why homeowners call Bernardino Martin for air conditioning service",
    trustPoints: [
      { title: "Licensed, local service", description: "We understand how Los Angeles heat affects equipment and how to service systems for real local demand." },
      { title: "Professional diagnostics", description: "We look at performance and system condition together instead of guessing from a single symptom." },
      { title: "Clear recommendations", description: "You get practical next steps and straightforward communication about maintenance, repair, or upgrade needs." },
      { title: "Fast booking support", description: "Phone and online booking make it easy to move from interest to scheduled service." },
    ],
    ctaHeading: "Book air conditioning service in Los Angeles today",
    ctaBody: "Schedule a cooling visit with Bernardino Martin and keep your Los Angeles home comfortable before the next heat wave arrives.",
  },
  {
    slug: "ac-repair-los-angeles",
    title: "AC Repair in Los Angeles | Bernardino Martin HVAC",
    metaDescription: "Professional ac repair services in Los Angeles. Call 818-400-0227.",
    heroLabel: "Repair Experts",
    heroTitle: "AC Repair in Los Angeles",
    heroSubtitle: "Fast, professional air conditioner repair for Los Angeles homes dealing with weak cooling, system shutdowns, and summer breakdowns.",
    heroImage: { src: "/images/svc-repair-ac.webp", alt: "Air conditioner repair service in Los Angeles" },
    introHeading: "Repair Service Built for Los Angeles Summers",
    introParagraphs: [
      "When an air conditioner stops working in Los Angeles, comfort disappears quickly. Bernardino Martin provides AC repair in Los Angeles for homeowners who need quick diagnostics, clean workmanship, and a realistic path back to dependable cooling. From systems that will not turn on to units that cool unevenly or run constantly, we focus on identifying the root issue and restoring reliable operation.",
      "Air conditioning failures are not always dramatic at first. Some systems still run but struggle to keep up, while others blow warm air, short cycle, trip breakers, or make unusual noises that warn of a bigger problem ahead. We evaluate refrigerant-side symptoms, electrical failures, thermostat communication, airflow restrictions, and component wear so the repair plan actually addresses what is wrong.",
      "Our repair process is designed to help Los Angeles homeowners move quickly from uncertainty to action. We explain the issue clearly, lay out repair options, and help you decide whether the system is worth repairing or whether a larger upgrade would provide better long-term value.",
    ],
    galleryHeading: "AC repair work for homes across Los Angeles",
    galleryImages: [
      { src: "/images/svc-repair-ac.webp", alt: "Residential AC repair visit" },
      { src: "/images/real-diagnostics.webp", alt: "Technician diagnosing cooling issues" },
      { src: "/images/ac-repair.webp", alt: "Air conditioning repair and condenser service" },
      { src: "/images/real-rooftop-hvac.webp", alt: "Cooling repair on rooftop HVAC equipment" },
    ],
    systemsHeading: "AC systems we repair",
    systemsIntro: "Our Los Angeles repair work covers high-efficiency AC units, ductless mini-splits, rooftop systems, and conventional central air equipment from major brands.",
    systems: [
      { title: "High-efficiency cooling systems", description: "We repair modern equipment without losing sight of airflow, controls, and setup issues that can mimic bigger failures." },
      { title: "Mini-split cooling systems", description: "Ductless systems need targeted diagnostics for communication issues, drainage, fan performance, and cooling output." },
      { title: "Central split systems", description: "Traditional air conditioners still require careful electrical and refrigerant troubleshooting to restore steady cooling." },
      { title: "Light commercial rooftop units", description: "We also support rooftop equipment used in small buildings where cooling downtime affects both staff and customers." },
    ],
    inlineHeading: "Repair decisions should feel clear, not rushed",
    inlineBody: "A professional repair visit should tell you whether the problem is isolated, recurring, or part of a larger decline in system performance. Bernardino Martin helps Los Angeles homeowners make confident decisions based on actual condition, expected reliability, and the cost of repeated breakdowns.",
    inlineImage: { src: "/images/ac-repair.webp", alt: "Detailed AC repair work on cooling equipment" },
    servicesHeading: "Our Los Angeles AC repair services",
    services: [
      "No-cool and warm-air troubleshooting",
      "Electrical component diagnosis",
      "Thermostat and control issues",
      "Airflow and circulation corrections",
      "Fan motor and capacitor replacement support",
      "Emergency repair scheduling",
      "Older system repair guidance",
      "Post-repair system performance checks",
    ],
    trustHeading: "Why Los Angeles homeowners choose us for AC repair",
    trustPoints: [
      { title: "Fast local response", description: "We know AC failures in Los Angeles need urgent attention when temperatures start climbing." },
      { title: "Repair-first mindset", description: "We diagnose carefully and help you understand whether a repair is the right move before pushing replacement." },
      { title: "Professional presentation", description: "Clear explanations, clean work areas, and straightforward communication keep the repair process stress-free." },
      { title: "Easy conversion path", description: "Phone and online booking options make it simple to move from urgent need to scheduled repair." },
    ],
    ctaHeading: "Need AC repair in Los Angeles right now?",
    ctaBody: "Call Bernardino Martin at 818-400-0227 for professional AC repair and quick scheduling throughout Los Angeles.",
  },
  {
    slug: "mini-split-service-los-angeles",
    title: "Mini Split Service in Los Angeles | Bernardino Martin HVAC",
    metaDescription: "Professional mini split service in Los Angeles. Call 818-400-0227.",
    heroLabel: "Ductless Comfort",
    heroTitle: "Mini Split Service in Los Angeles",
    heroSubtitle: "Installation support, repair, and maintenance for ductless mini-split systems in Los Angeles homes, additions, and upgraded comfort zones.",
    heroImage: { src: "/images/svc-ductless.webp", alt: "Mini split service in a Los Angeles home" },
    introHeading: "Ductless Service for Modern Los Angeles Homes",
    introParagraphs: [
      "Mini-split systems have become one of the most useful comfort upgrades for Los Angeles homes because they fit real-world situations so well. A converted garage, a new ADU, an upstairs bedroom that never cools evenly, or a home that does not have good duct access can all benefit from ductless climate control. Bernardino Martin provides mini split service in Los Angeles for homeowners who want efficient targeted comfort without the limitations of a full ducted redesign.",
      "Because mini-splits rely on precise controls and quiet efficient performance, service quality matters. A system can still run while suffering from poor drainage, reduced airflow, dirty coils, communication errors, or installation details that affect comfort and longevity. We inspect indoor heads, outdoor equipment, refrigerant-side symptoms, and overall system behavior so owners can understand how their ductless equipment is really performing.",
      "Mini-split service also supports better efficiency. These systems are often chosen because they can cool and heat targeted rooms without the energy losses associated with older ductwork. Bernardino Martin helps Los Angeles homeowners protect that efficiency with maintenance, repairs, and practical recommendations that preserve quiet operation and steady room comfort.",
    ],
    galleryHeading: "Mini-split installations and ductless service work",
    galleryImages: [
      { src: "/images/svc-ductless.webp", alt: "Indoor ductless mini-split service" },
      { src: "/images/svc-ductless-new.png", alt: "New mini-split installation support" },
      { src: "/images/svc-hvac-install-new.png", alt: "High-efficiency comfort system installation" },
      { src: "/images/technician.webp", alt: "Technician reviewing ductless system setup" },
    ],
    systemsHeading: "Mini-split systems we support",
    systemsIntro: "We work with single-zone and multi-zone ductless systems, inverter-driven comfort equipment, and hybrid layouts that combine mini-splits with existing HVAC systems.",
    systems: [
      { title: "Single-zone mini-splits", description: "Ideal for bedrooms, studios, garages, and office spaces that need independent climate control and efficient operation." },
      { title: "Multi-zone ductless systems", description: "We help maintain and service multi-room systems that rely on coordinated indoor heads and outdoor unit performance." },
      { title: "Heat-and-cool inverter systems", description: "Modern inverter mini-splits need clean servicing and accurate diagnostics to preserve quiet efficiency and steady temperature control." },
      { title: "Supplemental comfort zones", description: "Mini-splits often solve hot and cold spots in Los Angeles homes where existing ducts no longer deliver balanced comfort." },
    ],
    inlineHeading: "A ductless system should feel seamless inside the home",
    inlineBody: "Mini-splits are popular because they can disappear into daily life while keeping specific rooms comfortable. Our service approach protects that convenience by focusing on cleanliness, control performance, and the smooth operation that Los Angeles homeowners expect from ductless equipment.",
    inlineImage: { src: "/images/svc-ductless-new.png", alt: "Ductless mini-split wall unit installation" },
    servicesHeading: "Our Los Angeles mini-split services",
    services: [
      "Mini-split diagnostics and performance checks",
      "Ductless maintenance and cleaning",
      "Indoor head airflow evaluation",
      "Drainage and moisture issue troubleshooting",
      "Multi-zone system support",
      "Comfort planning for additions and ADUs",
      "Repair recommendations for ductless equipment",
      "Seasonal tune-ups for year-round use",
    ],
    trustHeading: "Why Los Angeles homeowners trust us with ductless systems",
    trustPoints: [
      { title: "Ductless-specific knowledge", description: "Mini-splits need a different service mindset than conventional central air, and we work accordingly." },
      { title: "Clean installation standards", description: "We value neat presentation and system layouts that look intentional inside finished living spaces." },
      { title: "Efficient comfort focus", description: "Our service protects the quiet, room-by-room comfort that makes mini-splits so useful in Los Angeles homes." },
      { title: "Easy next step", description: "Call or book online when you are ready to schedule service, maintenance, or ductless planning support." },
    ],
    ctaHeading: "Book mini-split service in Los Angeles",
    ctaBody: "Call 818-400-0227 to schedule mini-split service, maintenance, or repair with Bernardino Martin.",
  },
  {
    slug: "furnace-service-los-angeles",
    title: "Furnace Service in Los Angeles | Bernardino Martin HVAC",
    metaDescription: "Professional furnace service in Los Angeles. Call 818-400-0227.",
    heroLabel: "Heating Support",
    heroTitle: "Furnace Service in Los Angeles",
    heroSubtitle: "Dependable heating maintenance, troubleshooting, and repair support for Los Angeles furnace systems before cold weather arrives.",
    heroImage: { src: "/images/svc-heating-maint.webp", alt: "Furnace service and heating maintenance in Los Angeles" },
    introHeading: "Heating Service That Keeps Los Angeles Homes Ready",
    introParagraphs: [
      "Los Angeles may not face the same winter conditions as colder regions, but dependable furnace service still matters. Cold mornings, damp evenings, and older heating equipment can quickly make a home uncomfortable when temperatures drop. Bernardino Martin provides furnace service in Los Angeles for homeowners who want steady heat, cleaner operation, and fewer surprises at the start of the heating season.",
      "A furnace that sits unused for long periods can develop issues that do not show up until the first time it is needed. Dirty burners, airflow restrictions, thermostat problems, aging motors, and neglected maintenance can all affect how reliably the system starts and how evenly it heats the home. We service Los Angeles furnace systems with a focus on practical operation, safety, and comfort.",
      "Professional furnace service also helps homeowners make better long-term decisions. Some systems simply need cleaning and calibration, while others need repair planning or a more efficient replacement strategy. Bernardino Martin provides heating support that explains those options clearly, so Los Angeles homeowners can balance comfort, cost, and reliability without feeling rushed.",
    ],
    galleryHeading: "Heating service and furnace maintenance work",
    galleryImages: [
      { src: "/images/svc-heating-maint.webp", alt: "Heating maintenance service visit" },
      { src: "/images/svc-install-heating.webp", alt: "Furnace installation and setup support" },
      { src: "/images/heating.webp", alt: "Residential heating equipment service" },
      { src: "/images/svc-repair-heating.webp", alt: "Repair work on a heating system" },
    ],
    systemsHeading: "Heating systems we service",
    systemsIntro: "We support furnace systems, high-efficiency heating equipment, hybrid heat solutions, and comfort controls that help Los Angeles homes stay warm without wasted energy.",
    systems: [
      { title: "Gas furnace systems", description: "We help maintain furnace performance, ignition reliability, and airflow for homes that still depend on gas heat during colder weather." },
      { title: "Electric heating systems", description: "Electric heating components still need inspection, thermostat coordination, and seasonal service to perform dependably." },
      { title: "High-efficiency comfort systems", description: "Modern heating equipment benefits from careful maintenance that protects both efficiency and indoor comfort." },
      { title: "Integrated thermostat systems", description: "Heating performance depends on controls as much as equipment, especially in homes with mixed-age HVAC setups." },
    ],
    inlineHeading: "Seasonal furnace service protects comfort before problems grow",
    inlineBody: "Many heating problems feel minor until the first cold week exposes them. Our Los Angeles furnace service is built to find those weak points early, restore consistent heating, and help homeowners avoid reactive emergency calls later in the season.",
    inlineImage: { src: "/images/svc-heating-new.png", alt: "Technician reviewing a heating system inside a home" },
    servicesHeading: "Our Los Angeles furnace services",
    services: [
      "Seasonal furnace tune-ups",
      "Heating diagnostics and system checks",
      "Airflow and thermostat review",
      "Gas and electric heating support",
      "Repair planning for older furnace systems",
      "Comfort balancing for uneven heat",
      "Safety-minded performance evaluation",
      "Service for homes and light commercial spaces",
    ],
    trustHeading: "Why Los Angeles homeowners choose us for furnace service",
    trustPoints: [
      { title: "Seasonal readiness", description: "We help homeowners avoid first-use breakdowns by servicing systems before colder weather arrives." },
      { title: "Honest heating guidance", description: "You get clear recommendations on tune-ups, repairs, and upgrades based on actual system condition." },
      { title: "Professional workmanship", description: "Careful service and strong communication keep furnace visits straightforward and low-stress." },
      { title: "Simple booking options", description: "Call 818-400-0227 or book online when your Los Angeles heating system needs attention." },
    ],
    ctaHeading: "Schedule furnace service in Los Angeles",
    ctaBody: "Call Bernardino Martin at 818-400-0227 for furnace service that keeps your Los Angeles home ready for cooler weather.",
  },
];
