import type { KeywordPageData } from "./keyword-page";

export const keywordPagesB: KeywordPageData[] = [
  {
    slug: "heat-pump-los-angeles",
    title: "Heat Pump in Los Angeles | Bernardino Martin HVAC",
    metaDescription: "Professional heat pump services in Los Angeles. Call 818-400-0227.",
    heroLabel: "Heat Pump Solutions",
    heroTitle: "Heat Pump Service in Los Angeles",
    heroSubtitle: "Smart heating and cooling support for Los Angeles homeowners exploring efficient heat pump systems and year-round comfort upgrades.",
    heroImage: { src: "/images/svc-hvac-install-new.png", alt: "Heat pump installation and service in Los Angeles" },
    introHeading: "Efficient Heat Pump Comfort for Los Angeles Homes",
    introParagraphs: [
      "Heat pumps make a lot of sense in Los Angeles because the local climate allows one efficient system to handle both cooling and heating for much of the year. Bernardino Martin provides heat pump service in Los Angeles for homeowners who want cleaner energy use, better comfort control, and flexible system options for older homes, renovations, and new installations.",
      "A heat pump system depends on more than the outdoor unit. Airflow, thermostat controls, duct conditions, room layout, and overall equipment sizing all shape real-world results. In Los Angeles, where homeowners often care about both cooling efficiency and mild-season heating performance, these details matter. We work with central heat pumps, ductless heat pump systems, and hybrid comfort solutions that combine different equipment strategies.",
      "For many Los Angeles homeowners, heat pumps also represent a long-term upgrade decision rather than a simple repair call. Bernardino Martin helps customers compare current system performance with newer efficient options, and we provide maintenance and support that protects existing heat pump equipment as well.",
    ],
    galleryHeading: "Heat pump systems, installs, and service support",
    galleryImages: [
      { src: "/images/svc-hvac-install-new.png", alt: "Modern heat pump installation work" },
      { src: "/images/svc-ductless-new.png", alt: "Ductless heat pump style mini-split system" },
      { src: "/images/real-rooftop-hvac.webp", alt: "High-efficiency HVAC system setup" },
      { src: "/images/svc-install-thermostat.webp", alt: "Thermostat integration for heat pump systems" },
    ],
    systemsHeading: "Heat pump systems we work with",
    systemsIntro: "Our Los Angeles services support all-electric comfort systems, ducted high-efficiency heat pumps, mini-split heat pump units, and control upgrades that help them perform better.",
    systems: [
      { title: "Ducted heat pump systems", description: "Whole-home heat pumps need proper airflow and control setup to deliver comfortable cooling and heating across multiple rooms." },
      { title: "Mini-split heat pumps", description: "Ductless heat pump systems are ideal for zone control, additions, and targeted comfort in spaces with limited duct access." },
      { title: "High-efficiency inverter systems", description: "Inverter-driven heat pumps provide smooth comfort when they are maintained and calibrated correctly." },
      { title: "Thermostat and controls integration", description: "Modern controls help heat pump systems operate more efficiently and respond better to changing indoor conditions." },
    ],
    inlineHeading: "Heat pump comfort works best when the full system is planned well",
    inlineBody: "Homeowners often focus on the main equipment, but the best heat pump results come from the full comfort strategy: airflow, controls, room balance, and realistic expectations for the way Los Angeles homes use heating and cooling throughout the year.",
    inlineImage: { src: "/images/svc-install-thermostat.webp", alt: "Control setup for a high-efficiency heat pump system" },
    servicesHeading: "Our Los Angeles heat pump services",
    services: [
      "Heat pump diagnostics and maintenance",
      "System performance reviews",
      "Heating and cooling efficiency guidance",
      "Mini-split and ducted heat pump support",
      "Thermostat and controls setup",
      "Comfort planning for system upgrades",
      "Repair recommendations for existing units",
      "New installation consultation",
    ],
    trustHeading: "Why Los Angeles homeowners call Bernardino Martin for heat pump help",
    trustPoints: [
      { title: "Local climate understanding", description: "We help homeowners choose and service heat pumps based on how Los Angeles actually uses heating and cooling." },
      { title: "System-level thinking", description: "Airflow, controls, and layout matter, and we account for all of them when evaluating heat pump performance." },
      { title: "Modern comfort expertise", description: "From ductless systems to high-efficiency whole-home setups, we work with current comfort technology in a practical way." },
      { title: "Clear conversion path", description: "Phone and online booking make it easy to schedule service or start planning a Los Angeles heat pump project." },
    ],
    ctaHeading: "Talk to us about heat pumps in Los Angeles",
    ctaBody: "Call 818-400-0227 to schedule heat pump service or discuss an efficient comfort upgrade for your Los Angeles home.",
  },
  {
    slug: "solar-optimization-los-angeles",
    title: "Solar Optimization in Los Angeles | Bernardino Martin HVAC",
    metaDescription: "Professional solar optimization services in Los Angeles. Call 818-400-0227.",
    heroLabel: "Solar Performance",
    heroTitle: "Solar Optimization in Los Angeles",
    heroSubtitle: "Performance-focused solar service for Los Angeles homes that want stronger output, cleaner systems, and smarter energy use.",
    heroImage: { src: "/images/real-solar-install.webp", alt: "Solar optimization work on rooftop panels in Los Angeles" },
    introHeading: "Better Solar Performance for Los Angeles Homes",
    introParagraphs: [
      "Installing solar is only the beginning. To get the most value from a system in Los Angeles, homeowners need ongoing solar optimization that keeps production strong and catches underperformance before it becomes expensive. Bernardino Martin provides solar optimization in Los Angeles for homeowners who want better visibility into system output, cleaner panels, more reliable inverter performance, and a smarter connection between solar generation and overall energy use.",
      "Solar systems in Los Angeles deal with dust, heat, seasonal debris, and changing energy habits inside the home. A system that looked perfect after installation can slowly lose efficiency if cleaning, monitoring, or component checks are ignored. We help customers review system condition, identify practical maintenance needs, and understand where their energy strategy can improve.",
      "Bernardino Martin treats solar optimization as both a technical and practical service. Homeowners want solar to reduce bills, support reliable energy use, and feel worth the investment. Our Los Angeles solar work is designed to support those outcomes with professional presentation and straightforward recommendations.",
    ],
    galleryHeading: "Solar optimization and rooftop system performance work",
    galleryImages: [
      { src: "/images/real-solar-install.webp", alt: "Rooftop solar optimization service" },
      { src: "/images/real-solar-test.webp", alt: "Testing solar performance on a Los Angeles roof" },
      { src: "/images/solar-service.webp", alt: "Solar panel service and inspection" },
      { src: "/images/svc-solar-maintenance-new.png", alt: "Solar maintenance support and cleaning" },
    ],
    systemsHeading: "Optimization systems and upgrades we support",
    systemsIntro: "We work with rooftop solar arrays, inverter systems, high-efficiency energy strategies, battery-ready planning, and connected equipment that helps Los Angeles homeowners get more from solar.",
    systems: [
      { title: "Solar production monitoring", description: "Understanding how your system is actually performing helps catch declines early and supports smarter maintenance decisions." },
      { title: "Panel cleaning and upkeep planning", description: "Clean panels and regular condition checks help maintain output, especially in dusty Los Angeles environments." },
      { title: "Inverter and electrical performance review", description: "Solar output depends on more than the panels alone, and inverter-side issues can quietly reduce overall system value." },
      { title: "Energy efficiency alignment", description: "We help homeowners pair solar performance with HVAC, irrigation, and broader energy habits for better long-term results." },
    ],
    inlineHeading: "Optimization connects solar hardware with real household savings",
    inlineBody: "A solar system performs best when it is clean, monitored, and matched to the way the household uses energy. Our Los Angeles solar optimization service helps close that gap so homeowners can get stronger day-to-day value from the system they already own.",
    inlineImage: { src: "/images/solar-service.webp", alt: "Inline image of solar service and optimization support" },
    servicesHeading: "Our Los Angeles solar optimization services",
    services: [
      "Solar performance reviews",
      "Panel cleaning and maintenance support",
      "Inverter troubleshooting guidance",
      "Energy-use optimization planning",
      "Battery and backup readiness discussions",
      "System condition inspections",
      "Solar-powered irrigation coordination",
      "Long-term efficiency recommendations",
    ],
    trustHeading: "Why homeowners trust Bernardino Martin for solar optimization",
    trustPoints: [
      { title: "Performance-focused service", description: "We help homeowners improve real solar output instead of treating the system as a set-it-and-forget-it install." },
      { title: "Energy strategy awareness", description: "Optimization works best when solar is considered alongside cooling, water use, and daily household demand." },
      { title: "Professional presentation", description: "Our recommendations stay practical, clear, and focused on value instead of turning the process into jargon." },
      { title: "Strong conversion support", description: "Call or book online whenever you are ready to improve solar performance at your Los Angeles property." },
    ],
    ctaHeading: "Improve your solar performance in Los Angeles",
    ctaBody: "Call 818-400-0227 to schedule solar optimization service and get more value from your Los Angeles energy system.",
  },
  {
    slug: "plumbing-service-los-angeles",
    title: "Plumbing Service in Los Angeles | Bernardino Martin HVAC",
    metaDescription: "Professional plumbing service in Los Angeles. Call 818-400-0227.",
    heroLabel: "Residential Plumbing",
    heroTitle: "Plumbing Service in Los Angeles",
    heroSubtitle: "Professional plumbing support for Los Angeles homes dealing with leaks, older pipes, filtration needs, and smarter water management.",
    heroImage: { src: "/images/real-piping.webp", alt: "Plumbing service work in Los Angeles" },
    introHeading: "Plumbing Solutions for Older and Modern Los Angeles Homes",
    introParagraphs: [
      "Plumbing service in Los Angeles has to account for both aging infrastructure and modern expectations around water quality, leak protection, and efficiency. Bernardino Martin provides plumbing service in Los Angeles for homeowners who need practical repairs, thoughtful upgrades, and cleaner system performance throughout the home.",
      "A strong plumbing service visit should look beyond the most visible issue. A small leak may point to wider wear in the piping system, while poor water quality can affect appliances, fixtures, and comfort over time. We help Los Angeles homeowners evaluate pipe condition, filtration opportunities, fixture upgrades, water shutoff technology, and preventive improvements that reduce the risk of damage.",
      "Bernardino Martin delivers plumbing service with an emphasis on professionalism and long-term value. Whether you need pipe repair, drain-related support, filtration work, or a modern smart shutoff setup, we focus on clean execution and straightforward communication.",
    ],
    galleryHeading: "Plumbing repairs, piping work, and water system upgrades",
    galleryImages: [
      { src: "/images/real-piping.webp", alt: "Professional piping and plumbing service" },
      { src: "/images/real-pipe-repair.webp", alt: "Pipe repair and leak service work" },
      { src: "/images/real-copper-welding.webp", alt: "Copper pipe work for residential plumbing" },
      { src: "/images/moen-smart-water-shutoff.webp", alt: "Smart water shutoff valve installation" },
    ],
    systemsHeading: "Plumbing systems and upgrades we support",
    systemsIntro: "We work with supply piping, smart water protection devices, filtration systems, and plumbing upgrades that help Los Angeles homes stay protected and efficient.",
    systems: [
      { title: "Whole-home piping systems", description: "We evaluate aging pipe conditions and support repairs or upgrades that improve reliability and reduce hidden leak risk." },
      { title: "Water filtration systems", description: "Filtration and treatment upgrades help Los Angeles homeowners improve water quality and protect fixtures from buildup." },
      { title: "Smart shutoff protection", description: "Connected shutoff systems can detect problems early and reduce the chance of major water damage inside the home." },
      { title: "Fixture and water-use improvements", description: "Modern plumbing upgrades can support daily convenience while aligning with conservation-minded living in Southern California." },
    ],
    inlineHeading: "Great plumbing service protects the house beyond today's repair",
    inlineBody: "A leak or fixture problem is often the visible symptom of a larger maintenance story. We approach Los Angeles plumbing service with a preventative mindset so customers can fix immediate issues while strengthening the rest of the system at the same time.",
    inlineImage: { src: "/images/moen-smart-water-shutoff.webp", alt: "Smart plumbing system protection for Los Angeles homes" },
    servicesHeading: "Our Los Angeles plumbing services",
    services: [
      "Leak detection and pipe repair",
      "Fixture replacement and upgrades",
      "Water filtration support",
      "Soft water and reverse osmosis planning",
      "Smart shutoff valve installation",
      "Drain and cleanup system guidance",
      "Water quality improvement recommendations",
      "Residential plumbing diagnostics",
    ],
    trustHeading: "Why Los Angeles homeowners choose Bernardino Martin for plumbing service",
    trustPoints: [
      { title: "Home protection mindset", description: "We focus on reducing water damage risk and improving system reliability, not just patching the visible symptom." },
      { title: "Clean, professional work", description: "Good plumbing service should feel organized and respectful from the first conversation to the final result." },
      { title: "Modern upgrade awareness", description: "From filtration to smart shutoff systems, we help Los Angeles homeowners bring older plumbing into a more modern standard." },
      { title: "Easy conversion path", description: "Direct phone and online booking make it simple to schedule plumbing service when you are ready." },
    ],
    ctaHeading: "Book plumbing service in Los Angeles",
    ctaBody: "Call 818-400-0227 to schedule professional plumbing service and water-system support throughout Los Angeles.",
  },
  {
    slug: "landscaping-services-los-angeles",
    title: "Landscaping Services in Los Angeles | Bernardino Martin HVAC",
    metaDescription: "Professional landscaping services in Los Angeles. Call 818-400-0227.",
    heroLabel: "Outdoor Design",
    heroTitle: "Landscaping Services in Los Angeles",
    heroSubtitle: "Designed-for-LA outdoor improvements with clean installation, practical plant choices, and spaces that feel polished year-round.",
    heroImage: { src: "/images/svc-landscaping.png", alt: "Landscaping services in Los Angeles" },
    introHeading: "Landscaping That Fits the Way Los Angeles Lives Outdoors",
    introParagraphs: [
      "Landscaping services in Los Angeles need to balance style, durability, and water-conscious planning. Bernardino Martin helps homeowners create outdoor spaces that look polished while still fitting Southern California conditions and year-round use. From front-yard updates to backyard transformations, our Los Angeles landscaping services are built around layout, plant selection, grade transitions, and material choices that make a space easier to enjoy and easier to maintain.",
      "Because Los Angeles properties vary so much, a professional landscape plan has to respond to the lot itself. A sunny front yard in the Valley, a compact side yard in central Los Angeles, or a larger entertaining space on the Westside all call for different decisions around sod, planters, planting beds, drainage, and irrigation support.",
      "Our landscaping work is also shaped by how homeowners want to use the space after installation. Some want a cleaner family yard. Others want stronger curb appeal before selling, while many simply want a more finished outdoor environment that feels intentional. Bernardino Martin provides Los Angeles landscaping services with a clear process, strong presentation, and practical recommendations that help the final space feel cohesive instead of pieced together.",
    ],
    galleryHeading: "Landscape transformations and outdoor installation work",
    galleryImages: [
      { src: "/images/svc-landscaping.png", alt: "Custom landscaping installation" },
      { src: "/images/svc-planting.png", alt: "Planting and bed installation for Los Angeles homes" },
      { src: "/images/svc-sod-installation.png", alt: "Finished sod installation project" },
      { src: "/images/svc-smart-irrigation.png", alt: "Landscape paired with smart irrigation planning" },
    ],
    systemsHeading: "Landscape systems and features we build around",
    systemsIntro: "Our landscaping service connects design with practical outdoor systems like irrigation planning, sod installation, planting beds, and low-maintenance material choices.",
    systems: [
      { title: "Water-wise landscape layouts", description: "We help Los Angeles homeowners create spaces that look strong while using plant and ground-cover choices suited to local conditions." },
      { title: "Sod and lawn systems", description: "A finished lawn depends on grading, preparation, and a realistic maintenance strategy after installation." },
      { title: "Planters and planted zones", description: "Structured planting areas add character and make larger yards feel organized instead of empty." },
      { title: "Integrated irrigation planning", description: "Landscape projects work better long term when watering needs are considered from the start." },
    ],
    inlineHeading: "Professional landscaping should improve the whole property experience",
    inlineBody: "A good outdoor project changes more than appearances. It can improve curb appeal, make maintenance easier, and create spaces people actually want to use. Our Los Angeles landscaping service is designed to deliver that broader value with a polished final presentation.",
    inlineImage: { src: "/images/svc-planting.png", alt: "Inline landscaping image with planters and planting" },
    servicesHeading: "Our Los Angeles landscaping services",
    services: [
      "Front yard and backyard landscape design",
      "Planting and garden bed installation",
      "Sod planning and lawn creation",
      "Mulch and ground cover updates",
      "Low-maintenance outdoor layout support",
      "Retaining wall and border coordination",
      "Irrigation-aware design planning",
      "Seasonal outdoor refresh projects",
    ],
    trustHeading: "Why Los Angeles homeowners trust Bernardino Martin for landscaping",
    trustPoints: [
      { title: "Design with practicality", description: "We build outdoor spaces that look great without ignoring long-term care and water use." },
      { title: "Polished installation", description: "Clean execution and strong finish quality help landscaping projects feel complete and professional." },
      { title: "Responsive local service", description: "We understand the lot conditions, climate, and lifestyle priorities that shape landscaping work in Los Angeles." },
      { title: "Ready-to-book process", description: "Call or book online when you are ready to move your outdoor project forward." },
    ],
    ctaHeading: "Start your Los Angeles landscaping project",
    ctaBody: "Call 818-400-0227 to schedule landscaping services and create a more polished outdoor space in Los Angeles.",
  },
];
