import type { KeywordPageData } from "./keyword-page";

export const keywordPagesC: KeywordPageData[] = [
  {
    slug: "sod-installation-los-angeles",
    title: "Sod Installation in Los Angeles | Bernardino Martin HVAC",
    metaDescription: "Professional sod installation services in Los Angeles. Call 818-400-0227.",
    heroLabel: "Lawn Installation",
    heroTitle: "Sod Installation in Los Angeles",
    heroSubtitle: "Fresh lawn installation for Los Angeles homes that want cleaner curb appeal, faster transformation, and a more finished outdoor look.",
    heroImage: { src: "/images/svc-sod-installation.png", alt: "Sod installation project in Los Angeles" },
    introHeading: "Fast Lawn Transformation with Professional Sod Installation",
    introParagraphs: [
      "Sod installation is one of the fastest ways to change the look of a Los Angeles property. Bernardino Martin provides sod installation in Los Angeles for homeowners who want a cleaner yard, better curb appeal, and a lawn that feels intentionally finished rather than patchy or temporary. Good sod work is not just about laying grass. It depends on soil prep, grading, water planning, and choosing a lawn approach that makes sense for local conditions and the way the property will actually be used.",
      "Many Los Angeles homeowners choose sod because they want usable outdoor space quickly. Bare dirt, uneven growth, and worn-out lawns can make an otherwise attractive property feel neglected. A professional sod installation addresses that problem with a more complete process, from preparing the base to supporting better rooting after placement.",
      "Sod installation also fits larger landscape upgrades. It can frame planting zones, soften hardscape-heavy yards, and make family spaces feel more inviting. Our Los Angeles sod projects are built around strong presentation, realistic aftercare guidance, and the goal of giving homeowners a lawn they are proud to show.",
    ],
    galleryHeading: "Sod installation projects and lawn-ready outdoor spaces",
    galleryImages: [
      { src: "/images/svc-sod-installation.png", alt: "Completed sod installation in a residential yard" },
      { src: "/images/svc-landscaping.png", alt: "Landscaping project paired with new sod" },
      { src: "/images/svc-smart-irrigation.png", alt: "Irrigation-ready lawn zone for new sod" },
      { src: "/images/hero-home.webp", alt: "Finished home exterior with clean lawn presentation" },
    ],
    systemsHeading: "Lawn systems and support that improve sod performance",
    systemsIntro: "A successful sod install depends on preparation, water delivery, and long-term maintenance support instead of grass placement alone.",
    systems: [
      { title: "Prepared lawn foundations", description: "Proper grading and site prep help new sod root evenly and reduce issues with pooling, thin spots, or early stress." },
      { title: "Irrigation-aware installations", description: "New sod performs better when watering needs are planned from day one instead of treated as an afterthought." },
      { title: "Residential curb appeal upgrades", description: "Fresh sod can dramatically improve how a home presents from the street and how usable the yard feels overall." },
      { title: "Integrated landscape planning", description: "Sod works best when it is considered alongside planting beds, pathways, and the rest of the outdoor layout." },
    ],
    inlineHeading: "A new lawn should feel intentional, not temporary",
    inlineBody: "Professional sod installation creates a stronger visual impact because the lawn is part of a finished outdoor plan. We help Los Angeles homeowners turn uneven or tired yard space into something cleaner, greener, and easier to enjoy.",
    inlineImage: { src: "/images/hero-home.webp", alt: "Finished residential yard with strong curb appeal" },
    servicesHeading: "Our Los Angeles sod installation services",
    services: [
      "Residential sod installation",
      "Soil preparation and grading support",
      "Lawn refresh and replacement projects",
      "Landscape integration planning",
      "Watering and aftercare guidance",
      "Curb appeal improvement work",
      "Yard transformation consultation",
      "Sod installation for front and back yards",
    ],
    trustHeading: "Why Los Angeles homeowners choose Bernardino Martin for sod installation",
    trustPoints: [
      { title: "Strong visual results", description: "We approach sod installation as a finished property upgrade, not just a quick surface change." },
      { title: "Practical lawn planning", description: "Preparation, irrigation, and long-term maintenance all shape whether a new lawn actually succeeds." },
      { title: "Clean project execution", description: "Professional presentation and organized installation help the final yard feel intentional and high quality." },
      { title: "Easy next step", description: "Call 818-400-0227 or book online when you are ready to install new sod in Los Angeles." },
    ],
    ctaHeading: "Ready for sod installation in Los Angeles?",
    ctaBody: "Call Bernardino Martin at 818-400-0227 to schedule a sod installation consultation for your Los Angeles property.",
  },
  {
    slug: "planters-landscaping-los-angeles",
    title: "Planters Landscaping in Los Angeles | Bernardino Martin HVAC",
    metaDescription: "Professional planters landscaping services in Los Angeles. Call 818-400-0227.",
    heroLabel: "Planter Design",
    heroTitle: "Planters Landscaping in Los Angeles",
    heroSubtitle: "Structured planter and planting design that helps Los Angeles outdoor spaces feel layered, finished, and easier to maintain.",
    heroImage: { src: "/images/svc-planting.png", alt: "Planters landscaping design in Los Angeles" },
    introHeading: "Planter-Focused Landscaping That Adds Structure and Style",
    introParagraphs: [
      "Planters can completely change how an outdoor space feels. Bernardino Martin provides planters landscaping in Los Angeles for homeowners who want yards, patios, side spaces, and entry areas to feel more intentional and better designed. Planter zones help organize space, soften hardscape-heavy layouts, and introduce color and texture in a way that is easier to maintain than full-lawn concepts.",
      "Strong planter landscaping is about more than choosing attractive containers or adding greenery in empty corners. It depends on proportion, placement, drainage, sun exposure, plant selection, and how the planters connect to walkways, lawn zones, and seating areas. Bernardino Martin helps Los Angeles homeowners create planter layouts that feel cohesive and support the style of the home instead of looking like afterthoughts.",
      "Planters are also an excellent way to support water-wise landscaping in Los Angeles. They allow for targeted planting, easier irrigation control, and more selective use of color and greenery in spaces where traditional beds may not be ideal. Our planter landscaping work is built around a polished final result that looks professional and fits local living.",
    ],
    galleryHeading: "Planter landscapes, planting zones, and finished outdoor details",
    galleryImages: [
      { src: "/images/svc-planting.png", alt: "Decorative planter and planting installation" },
      { src: "/images/svc-landscaping.png", alt: "Outdoor space enhanced with planter landscaping" },
      { src: "/images/svc-smart-irrigation.png", alt: "Planter landscaping with smart watering support" },
      { src: "/images/svc-sod-installation.png", alt: "Planters combined with lawn and landscape design" },
    ],
    systemsHeading: "Planter systems and landscape features we build around",
    systemsIntro: "Planter-focused projects work best when they connect to the larger outdoor system, including irrigation planning, planting strategy, and yard layout.",
    systems: [
      { title: "Structured planting zones", description: "Planters help break large outdoor areas into more usable and visually balanced zones with stronger definition." },
      { title: "Water-conscious design", description: "Targeted planting areas support more controlled watering and maintenance than larger traditional landscape beds." },
      { title: "Hardscape-friendly landscaping", description: "Planters are a strong fit for Los Angeles homes with patios, driveways, walkways, and limited planting space." },
      { title: "Curb appeal layering", description: "Entry planters and architectural planting arrangements can make the front of a home feel much more complete." },
    ],
    inlineHeading: "Planter design brings focus and refinement to outdoor spaces",
    inlineBody: "A good planter layout gives a yard structure. It adds intentional color, shape, and softness in the places where outdoor areas need it most. Our Los Angeles planter landscaping service is designed to make those spaces feel planned rather than empty.",
    inlineImage: { src: "/images/svc-landscaping.png", alt: "Refined outdoor space with planter landscaping" },
    servicesHeading: "Our Los Angeles planter landscaping services",
    services: [
      "Planter layout design",
      "Planting zone installation",
      "Entry and patio planter upgrades",
      "Decorative planting arrangements",
      "Water-wise planter planning",
      "Integrated landscape refresh work",
      "Front yard curb appeal improvements",
      "Backyard visual enhancement projects",
    ],
    trustHeading: "Why Los Angeles homeowners choose Bernardino Martin for planter landscaping",
    trustPoints: [
      { title: "Design-minded execution", description: "We focus on planter projects that improve the overall look and flow of the property, not just add plants." },
      { title: "Practical local choices", description: "Plant selection, layout, and watering strategy all reflect what performs well in Los Angeles conditions." },
      { title: "Professional finish quality", description: "Our planter landscaping work is meant to feel clean, intentional, and visually complete." },
      { title: "Straightforward booking", description: "Call or book online when you are ready to bring more structure and style to your outdoor space." },
    ],
    ctaHeading: "Upgrade your Los Angeles yard with planter landscaping",
    ctaBody: "Call 818-400-0227 to schedule a planter landscaping consultation with Bernardino Martin in Los Angeles.",
  },
  {
    slug: "network-repair-los-angeles",
    title: "Network Repair in Los Angeles | Bernardino Martin HVAC",
    metaDescription: "Professional network repair services in Los Angeles. Call 818-400-0227.",
    heroLabel: "Connected Homes",
    heroTitle: "Network Repair in Los Angeles",
    heroSubtitle: "Professional troubleshooting and repair support for Los Angeles homes and businesses dealing with unstable internet, cabling problems, and smart-home connectivity issues.",
    heroImage: { src: "/images/svc-network.png", alt: "Network repair service in Los Angeles" },
    introHeading: "Network Repair for Homes That Need Reliable Connectivity",
    introParagraphs: [
      "Network problems affect more than convenience. In Los Angeles homes and small business environments, weak connectivity can disrupt work, security systems, streaming, smart-home controls, and everyday routines. Bernardino Martin provides network repair in Los Angeles for customers who need cleaner troubleshooting, stronger wired and wireless performance, and a more dependable digital setup overall.",
      "Many network issues are really infrastructure issues. A router may not be the problem if cabling is weak, a switch is misconfigured, or the home layout is creating dead zones the system was never designed to handle. We evaluate the physical setup, hardware relationships, and day-to-day usage patterns so customers in Los Angeles get repair guidance that reflects how the network is actually being used.",
      "Bernardino Martin treats network repair as a service experience, not a vague tech support conversation. We help customers understand what is failing, what needs to be corrected, and how a more stable network can support the rest of the connected home.",
    ],
    galleryHeading: "Network repair, cabling support, and connected-home service work",
    galleryImages: [
      { src: "/images/svc-network.png", alt: "Structured network troubleshooting and repair" },
      { src: "/images/happy-family-tech.webp", alt: "Connected home technology and reliable WiFi use" },
      { src: "/images/technician.webp", alt: "Professional technician reviewing network equipment" },
      { src: "/images/svc-install-thermostat.webp", alt: "Smart-home device connectivity support" },
    ],
    systemsHeading: "Network systems and connected equipment we support",
    systemsIntro: "We work with structured cabling, WiFi coverage setups, router and switch equipment, and smart-home devices that depend on reliable network performance.",
    systems: [
      { title: "Structured cabling systems", description: "Clean physical cabling helps eliminate many hidden connection problems and supports stronger long-term performance." },
      { title: "Whole-home WiFi setups", description: "Coverage problems are often repairable through better equipment placement, hardware adjustments, and network design corrections." },
      { title: "Smart-home device connectivity", description: "Thermostats, cameras, and voice assistants all depend on a stable network foundation to perform reliably." },
      { title: "Router and switching hardware", description: "Good network repair includes understanding whether the issue comes from hardware, layout, or infrastructure underneath." },
    ],
    inlineHeading: "A repaired network should feel stable, fast, and easy to live with",
    inlineBody: "Most customers do not want a more complicated network. They want a more dependable one. Our Los Angeles network repair service is built around solving practical connection problems so the technology fades back into the background and daily life works the way it should.",
    inlineImage: { src: "/images/happy-family-tech.webp", alt: "Reliable connected-home experience after network repair" },
    servicesHeading: "Our Los Angeles network repair services",
    services: [
      "WiFi performance troubleshooting",
      "Structured cabling repair support",
      "Router and switch review",
      "Dead zone reduction planning",
      "Smart-home connectivity troubleshooting",
      "Security camera network support",
      "Home office connection improvements",
      "General network stability diagnostics",
    ],
    trustHeading: "Why customers choose Bernardino Martin for network repair",
    trustPoints: [
      { title: "Practical diagnostics", description: "We focus on clear causes and real fixes instead of vague troubleshooting that leaves the problem unresolved." },
      { title: "Whole-system awareness", description: "Your network includes wiring, hardware, layout, and connected devices, and we account for all of them." },
      { title: "Professional presentation", description: "Clean communication and organized service help make technical work easier to understand and act on." },
      { title: "Fast booking options", description: "Call 818-400-0227 or book online to schedule network repair support in Los Angeles." },
    ],
    ctaHeading: "Need network repair in Los Angeles?",
    ctaBody: "Call Bernardino Martin at 818-400-0227 for professional network repair and connected-home troubleshooting in Los Angeles.",
  },
  {
    slug: "new-installation-los-angeles",
    title: "New Installation in Los Angeles | Bernardino Martin HVAC",
    metaDescription: "Professional new installation services in Los Angeles. Call 818-400-0227.",
    heroLabel: "New Installations",
    heroTitle: "New Installation Services in Los Angeles",
    heroSubtitle: "Professional installation support for Los Angeles homeowners upgrading HVAC, solar, plumbing, irrigation, and connected home systems.",
    heroImage: { src: "/images/real-crane-lift.webp", alt: "New equipment installation service in Los Angeles" },
    introHeading: "Professional Installation Work That Starts with a Plan",
    introParagraphs: [
      "New installation work should feel organized from the beginning. Bernardino Martin provides new installation services in Los Angeles for homeowners who want a clean, professional process when upgrading critical systems around the home. That can include HVAC replacements, solar-related equipment, irrigation upgrades, plumbing protection devices, thermostats, ductless units, and other comfort-focused improvements.",
      "Los Angeles homes often need installation strategies that respond to local realities rather than default packages. Older homes may need creative routing and updated support systems. Newer homes may need efficient add-ons that improve comfort and convenience without disrupting existing layouts. We help customers think through the full installation picture, including equipment placement, appearance, performance goals, and long-term maintenance considerations.",
      "Bernardino Martin approaches new installation work as a professional service experience. We want customers to feel confident that the upgrade will improve the home, fit the property, and support daily life instead of creating avoidable complications. If you are planning a new installation in Los Angeles, our team helps move the project from idea to execution with strong communication, polished presentation, and a clear focus on long-term results.",
    ],
    galleryHeading: "Recent installations and system upgrade work in Los Angeles",
    galleryImages: [
      { src: "/images/real-crane-lift.webp", alt: "Large equipment installation with crane support" },
      { src: "/images/svc-hvac-install-new.png", alt: "New HVAC installation project" },
      { src: "/images/svc-solar-install-new.png", alt: "Solar-related new installation support" },
      { src: "/images/moen-smart-water-shutoff.webp", alt: "Smart plumbing device installation" },
    ],
    systemsHeading: "Systems we install and upgrade",
    systemsIntro: "We support high-efficiency HVAC systems, solar and irrigation upgrades, smart home equipment, and practical home-service installations that improve comfort and performance.",
    systems: [
      { title: "High-efficiency HVAC systems", description: "New comfort equipment should be matched to the property and installed with attention to airflow, placement, and long-term reliability." },
      { title: "Solar and energy upgrades", description: "Installation planning matters when energy-related equipment needs to coordinate with existing electrical and household usage patterns." },
      { title: "Smart plumbing and irrigation systems", description: "Water management upgrades can improve protection, efficiency, and property care when the installation is planned well." },
      { title: "Connected home equipment", description: "Thermostats, network hardware, and smart controls benefit from clean integration instead of patchwork installation methods." },
    ],
    inlineHeading: "A new installation should improve the home immediately and hold up long term",
    inlineBody: "The best installations feel natural once they are complete. The equipment looks like it belongs, the system works the way the homeowner expected, and the upgrade clearly improves everyday comfort or convenience. That is the standard we aim for in Los Angeles installation work.",
    inlineImage: { src: "/images/svc-hvac-install-new.png", alt: "Inline image of new equipment installation work" },
    servicesHeading: "Our Los Angeles new installation services",
    services: [
      "HVAC replacement and installation support",
      "Mini-split and thermostat installs",
      "Solar-related upgrade installation",
      "Smart shutoff and plumbing device installs",
      "Irrigation system installation",
      "Network and smart-home equipment setup",
      "Comfort and control system upgrades",
      "Installation planning consultations",
    ],
    trustHeading: "Why Los Angeles homeowners call Bernardino Martin for installations",
    trustPoints: [
      { title: "Planning before placement", description: "We think through layout, performance, and appearance so the final result works as well as it looks." },
      { title: "Multi-service capability", description: "Our installation work spans comfort, energy, water, and connected-home improvements under one service umbrella." },
      { title: "Professional finish quality", description: "A new system should feel like a meaningful upgrade to the property, not a rushed add-on." },
      { title: "Easy conversion path", description: "Call 818-400-0227 or book online to start planning your Los Angeles installation project." },
    ],
    ctaHeading: "Start your new installation project in Los Angeles",
    ctaBody: "Call Bernardino Martin at 818-400-0227 to schedule new installation services and system upgrades in Los Angeles.",
  },
];
