import { ServiceDetailTemplate } from "./template";

export default function HvacAirFiltration() {
  return (
    <ServiceDetailTemplate
      serviceName="Electrostatic Air Filtration"
      slug="hvac-air-filtration"
      category="HVAC & Heating"
      categoryColor="blue"
      heroVideo="/videos/svc-hvac.mp4"
      heroImage="/images/svc-hvac-maint.webp"
      tagline="Eliminate odors, allergens, and airborne particles for cleaner indoor air"
      overview={[
        "Electrostatic air filters use an electrical charge to attract and capture airborne particles the same way a magnet attracts metal filings. As air passes through the filter media, particles as small as 0.1 microns — including bacteria, tobacco smoke, and fine dust — receive an opposing charge and are pulled firmly onto the filter surface, achieving capture rates that standard fiberglass filters cannot approach.",
        "Los Angeles residents face unique air quality challenges that standard HVAC filters aren't designed to handle. Seasonal wildfire smoke from fires across Southern California introduces ultrafine particles and toxic compounds into the outdoor air that seep indoors. Combined with year-round vehicle exhaust, pollen from non-native landscaping plants, and dry Santa Ana wind conditions that disturb dust, LA households benefit significantly from filtration that goes beyond basic particulate capture.",
        "Unlike disposable filters that get thrown away monthly and add up in cost and waste, electrostatic filters are washable and reusable. They slide into your existing filter slot without any ductwork modification, and because they are thinner and less restrictive than thick HEPA-style media filters, they don't create the airflow restriction that can reduce system efficiency. You simply remove them, rinse them with a garden hose, let them dry, and reinstall.",
      ]}
      keyBenefits={[
        "Removes up to 99% of airborne particles",
        "Eliminates pet dander, pollen, and wildfire smoke",
        "Reduces household odors",
        "No monthly filter replacement — washable and reusable",
        "Integrates with existing HVAC system",
        "Improves overall HVAC efficiency",
      ]}
      whatWeInclude={[
        "Air quality assessment",
        "System compatibility check",
        "Filter installation in existing ductwork",
        "Seal and bypass testing",
        "Before/after particle count test",
        "Cleaning and maintenance instructions",
        "System performance verification",
      ]}
      duration="2-4 hours"
      startingPrice="Starting at $299"
      relatedServices={[
        { name: "Duct Cleaning & Installation", slug: "hvac-ducts" },
        { name: "HVAC Maintenance", slug: "hvac-maintenance" },
        { name: "AC Installation", slug: "hvac-install-ac" },
      ]}
      cityLinks={[]}
      faqs={[
        {
          question: "How is an electrostatic filter different from a regular filter?",
          answer:
            "Standard fiberglass filters mechanically block particles above a certain size — they work like a physical screen. Electrostatic filters use an electrical charge (either passive, generated by airflow friction, or active, powered by a small electrical current) to attract particles the way a magnet attracts metal. This allows them to capture far smaller particles, including bacteria, smoke, and fine dust, without the airflow restriction of thick mechanical filters.",
        },
        {
          question: "Will an electrostatic filter help with Los Angeles wildfire smoke?",
          answer:
            "Yes — wildfire smoke primarily consists of ultrafine particles in the PM2.5 range, and electrostatic filtration is particularly effective at capturing particles in that size range. During wildfire events, we recommend keeping windows and doors closed and running your HVAC system continuously on fan mode to continuously cycle air through the electrostatic filter. This significantly reduces indoor smoke concentrations.",
        },
        {
          question: "How do I maintain an electrostatic filter?",
          answer:
            "Washable electrostatic filters should be removed and rinsed with a garden hose approximately once a month during periods of heavy use. Allow the filter to air-dry completely before reinstalling — typically 2–4 hours in the LA sun. The frame and charged media are durable and designed to last 5–10 years with proper care, making them far more economical than monthly disposable filter purchases.",
        },
        {
          question: "Can electrostatic filtration lower my energy bills?",
          answer:
            "Indirectly, yes. Dirty, clogged filters force your HVAC blower to work harder, increasing electricity consumption. Because electrostatic filters are cleaned rather than replaced and are less restrictive than thick media filters, your system maintains proper airflow, which reduces blower motor strain and keeps your system operating at its rated efficiency.",
        },
        {
          question: "What MERV rating do electrostatic filters have compared to standard filters?",
          answer:
            "Passive electrostatic filters typically achieve an effective MERV 8–12 rating. Active (powered) electrostatic precipitators can reach MERV 15–16. For comparison, the basic filters that come with most systems are MERV 1–4. MERV 8–10 is sufficient for most households, while allergy sufferers or households with pets benefit from higher ratings. We'll recommend the right option based on your specific air quality needs.",
        },
      ]}
    />
  );
}
